import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import ReduxProvider from "./providers/ReduxProvider";
import NextAuthProvider from "./providers/NextAuthProvider";
import AutoSignOut from "./components/AutoSignOut/AutoSignOut";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "E-commerce",
    template: "E-commerce | %s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <NextAuthProvider>
          <ReduxProvider>
            <AutoSignOut />
            <Navbar />
            {modal}
            {children}
          </ReduxProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
